apiVersion: v1
kind: Service
metadata:
  name: gamelobby-service-exposed
spec:
  selector:
    app: gamelobby
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
      nodePort: 31000
  type: NodePort